jobs:
- job: build_jdk
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/cf-ubuntu-jdk11-plus-buildjdk:latest
  steps:
  - checkout: none
  - bash: |
      whoami
      pwd
      ls -l
      env | sort
    displayName: show environment
  - bash: |
      set -ex
      if [ -d /tmp/plume-scripts ]; \
        then git -C /tmp/plume-scripts pull > /dev/null 2>&1 ; \
        else git -C /tmp clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git ; \
        fi
      eval `/tmp/plume-scripts/ci-info typetools`
      CI_REPOSITORY_URI=https://github.com/${CI_ORGANIZATION}/jdk.git
      if [ -d /jdk ]; \
        then git -C /jdk pull -q ${CI_REPOSITORY_URI} ${CI_BRANCH} ; \
        else git clone --depth 1 -q ${CI_REPOSITORY_URI} --branch ${CI_BRANCH} /jdk ; \
        fi
    displayName: pull or clone
  - bash: make -C /jdk images
    timeoutInMinutes: 90
    displayName: make images
  - bash: /jdk/build/*/images/jdk/bin/java -version
    displayName: version
  # - bash: make -C /jdk run-test-tier1
  #   displayName: make run-test-tier1
- job: build_jdk11u
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/cf-ubuntu-jdk11-plus-buildjdk:latest
  timeoutInMinutes: 0
  steps:
  - checkout: none
  - bash: |
      whoami
      pwd
      ls -l
      env | sort
    displayName: show environment
  - bash: |
      set -ex
      if [ -d /tmp/plume-scripts ]; \
        then git -C /tmp/plume-scripts pull > /dev/null 2>&1 ; \
        else git -C /tmp clone --depth 1 -q https://github.com/plume-lib/plume-scripts.git ; \
        fi
      eval `/tmp/plume-scripts/ci-info typetools`
      CI_REPOSITORY_URI=https://github.com/${CI_ORGANIZATION}/jdk11u.git
      if [ -d /jdk11u ]; \
        then git -C /jdk11u pull -q ${CI_REPOSITORY_URI} ${CI_BRANCH} ; \
        else git clone --depth 1 -q ${CI_REPOSITORY_URI} --branch ${CI_BRANCH} /jdk11u ; \
        fi
    displayName: pull or clone
  - bash: make -C /jdk11u images
    displayName: make images
  - bash: /jdk11u/build/*/images/jdk/bin/java -version
    displayName: version
  - bash: cd /jdk11u && git pull /jdk ${CI_BRANCH}
    displayName: git merge
  # - bash: make -C /jdk11u run-test-tier1
  #   timeoutInMinutes: 0
  #   displayName: make run-test-tier1
  # - bash: make -C /jdk11u JTREG="JOBS=1;TIMEOUT=8" :test/jdk:tier1
  - bash: make -C /jdk11u run-test TEST="jtreg:test/jdk:tier1" JTREG="TIMEOUT=8"
    timeoutInMinutes: 0
    displayName: make run-test-tier1

trigger:
  batch: true
